plugins {
    id 'idea'
    id 'fabric-loom' version '1.16-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id
}
loom {
    accessWidenerPath = file("src/main/resources/acceleratedrendering.accesswidener")
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.

    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Ladysnake Libs"
        url = 'https://maven.ladysnake.org/releases'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://raw.github.com/Sh1roCu/Sh1roCu_MCRepo/master/repository"
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "net.minecraft:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21.4:2025.01.19@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modRuntimeOnly "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation fabricApi.module("fabric-resource-loader-v0", project.fabric_version)
    modImplementation fabricApi.module("fabric-networking-api-v1", project.fabric_version)
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
    modImplementation("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:21.4.3")

    modCompileOnly "maven.modrinth:sodium:mc1.21.4-0.6.13-fabric"
    modCompileOnly "maven.modrinth:iris:1.8.5+1.21.4-fabric"
    modCompileOnly "maven.modrinth:geckolib:4.8"
    modCompileOnly "maven.modrinth:entity-model-features:3.2.4-fabric-1.21.4"
    modCompileOnly "maven.modrinth:immediatelyfast:1.3.4+1.21.4-fabric"
    modCompileOnly "maven.modrinth:axiom:6BFd0w5s"
    modCompileOnly "maven.modrinth:modern-ui:ZNr1nosu" //3.13.0.1

    compileOnly("com.moulberry:mixinconstraints:1.0.9")
    compileOnly("org.projectlombok:lombok:1.18.40")
    annotationProcessor("org.projectlombok:lombok:1.18.40")
    modCompileOnly "maven.modrinth:trinkets-canary:3.10.0-1.21.4"
    modCompileOnly "maven.modrinth:malilib:xTezyq2N"
    modCompileOnly "maven.modrinth:tweakermore:vQdcjuSM" // v3.27.0-mc1.21.1
//    modCompileOnly("cn.sh1rocu:touhoulittlemaid-fabric-1.21.1:0.7.0-neo1.5.2") {
//        transitive = false
//    }
    modCompileOnly "maven.modrinth:touhoulittlemaid-orihime:0.8.2-neo1.5.3+mc1.21.1"

    modCompileOnly "curse.maven:ftb-library-fabric-438495:7312255"

    include implementation("net.neoforged:bus:8.0.5")

//    api("io.github.spair:imgui-java-binding:$imguiVersion")
//    api("io.github.spair:imgui-java-lwjgl3:$imguiVersion") {
//        exclude group: "org.lwjgl"
//    }
//
//    implementation("io.github.spair:imgui-java-natives-windows:$imguiVersion")
//    implementation("io.github.spair:imgui-java-natives-linux:$imguiVersion")
//    implementation("io.github.spair:imgui-java-natives-macos:$imguiVersion")
    //implementation "com.github.tartaricacid:touhoulittlemaid-1.21.1:release-1.2.2"
}

processResources {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            mod_id           : mod_id,
            mod_name         : mod_name,
            mod_license      : mod_license,
            mod_version      : mod_version,
            mod_authors      : mod_authors,
            mod_description  : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching("fabric.mod.json") {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}